In [13]:
import pandas as pd

In [14]:
df=pd.read_parquet(r"D:\AI\Real projects\Academic_Advisor_Simple\data\raw\v_add_academic_info.parquet")

In [15]:
df

,student_id,diploma_gpa,diploma_type_id,diploma_state_id,diploma_country_sl,active
0,1.111,60.00,13.111,13.0,سورية,شهادة ثانوية تجارية
1,2.111,56.82,16.111,15.0,سورية,شهادة ثانوية أدبي
2,3.111,60.45,16.111,4.0,سورية,شهادة ثانوية أدبي
3,4.111,50.83,15.111,4.0,سورية,شهادة ثانوية علمي
4,5.111,67.27,13.111,5.0,سورية,شهادة ثانوية تجارية
...,...,...,...,...,...,...
32543,33700.111,69.90,51.111,4.0,سورية,الثانوي - علمي - منهاج دمشق
32544,33701.111,85.79,15.111,4.0,سورية,شهادة ثانوية علمي
32545,33702.111,65.59,51.111,5.0,سورية,الثانوي - علمي - منهاج دمشق
32546,33703.111,65.81,51.111,5.0,سورية,الثانوي - علمي - منهاج دمشق
32547,33704.111,71.00,51.111,4.0,سورية,الثانوي - علمي - منهاج دمشق

In [16]:
df.drop(columns=['diploma_state_id','diploma_country_sl','active'],inplace=True)

In [17]:
df['diploma_type_id'].value_counts()

diploma_type_id
15.111    29078
16.111     1557
51.111      952
13.111      529
19.111      129
52.111       58
26.111       51
14.111       31
25.111       24
10.111       17
20.111       16
60.111       11
65.111        9
9.111         7
31.111        6
32.111        6
69.111        6
21.111        5
18.111        5
59.111        5
70.111        5
58.111        4
63.111        3
61.111        3
27.111        2
22.111        2
71.111        2
68.111        1
Name: count, dtype: int64

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32548 entries, 0 to 32547
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   student_id       32548 non-null  float64
 1   diploma_gpa      32080 non-null  float64
 2   diploma_type_id  32524 non-null  float64
dtypes: float64(3)
memory usage: 763.0 KB

In [19]:
null_report = df.isna().sum().to_frame("null_count")
null_report["null_percent"] = (
null_report["null_count"] / len(df) * 100
).round(2)
null_report = null_report.sort_values("null_count", ascending=False)

In [20]:
null_report

                 null_count  null_percent
diploma_gpa             468          1.44
diploma_type_id          24          0.07
student_id                0          0.00

In [21]:
df.dropna(subset=['diploma_type_id'], inplace=True)

In [22]:
null_report = df.isna().sum().to_frame("null_count")
null_report["null_percent"] = (
null_report["null_count"] / len(df) * 100
).round(2)
null_report = null_report.sort_values("null_count", ascending=False)
null_report

                 null_count  null_percent
diploma_gpa             446          1.37
student_id                0          0.00
diploma_type_id           0          0.00

In [23]:
df['diploma_gpa'] = df['diploma_gpa'].ffill()

In [24]:
null_report = df.isna().sum().to_frame("null_count")
null_report["null_percent"] = (
null_report["null_count"] / len(df) *100
).round(2)
null_report = null_report.sort_values("null_count", ascending=False)
null_report

                 null_count  null_percent
student_id                0           0.0
diploma_gpa               0           0.0
diploma_type_id           0           0.0