In [1]:
import pandas as pd 
from paths import STUDENT_STATUS_PATH

In [2]:
pd.set_option("display.max_columns",100)

In [3]:
df=pd.read_parquet(STUDENT_STATUS_PATH)

In [8]:
df[df['finish_status']=='WITHDRAWN']

,student_status_id,student_id,part_id,degree_id,start_part_id,finish_part_id,grade_version_id,permanent_status_id,permanent_status_sl,study_mode,prev_gpa_points,prev_gpa_percent,gpa_percent,gpa_points,start_agpa_percent,start_agpa_points,start_total_in_courses,start_total_in_credits,end_total_in_courses,end_total_in_credits,end_agpa_percent,end_agpa_points,semester_reg_courses,semester_reg_credits,semester_pass_courses,semester_pass_credits,semester_fail_courses,semester_fail_credits,semester_in_courses,semester_in_credits,total_semesters,total_reg_courses,total_reg_credits,total_pass_courses,total_pass_credits,total_fail_courses,total_fail_credits,reg_total_semesters,finish_status,version_title_sl,degree_name_sl,degree_credits_count,start_level_id,start_level_name_short,end_level_name_short,start_level_name_pl
160,245684.111,139.111,20172.0,22.111,20172.0,20191.0,2.111,2.0,مقبول,C,0.00,0.0,26.6,0.33,37.2,0.86,0.0,0.0,10.0,21.0,26.6,0.33,5.0,12.0,1.0,2.0,4.0,10.0,10.0,21.0,15.0,67.0,165.0,13.0,32.0,53.0,130.0,12.0,WITHDRAWN,القرار الوزاري الموحد,إدارة (اختصاص عام),72.0,505.111,1,1,First Year
161,265784.111,139.111,20181.0,22.111,20172.0,20191.0,2.111,2.0,مقبول,C,0.33,26.6,0.0,0.00,26.6,0.33,10.0,21.0,10.0,21.0,26.6,0.33,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16.0,72.0,177.0,14.0,34.0,57.0,140.0,12.0,WITHDRAWN,القرار الوزاري الموحد,إدارة (اختصاص عام),72.0,505.111,1,1,First Year
162,267095.111,139.111,20182.0,22.111,20172.0,20191.0,2.111,17.0,ترقين قيد,C,0.00,0.0,0.0,0.00,26.6,0.33,10.0,21.0,10.0,21.0,26.6,0.33,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.0,72.0,177.0,14.0,34.0,57.0,140.0,12.0,WITHDRAWN,القرار الوزاري الموحد,إدارة (اختصاص عام),72.0,829.111,1,1,First Year
163,275429.111,139.111,20191.0,22.111,20172.0,20191.0,2.111,9.0,منسحب,C,0.00,0.0,0.0,0.00,26.6,0.33,10.0,21.0,10.0,21.0,26.6,0.33,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18.0,72.0,177.0,14.0,34.0,57.0,140.0,12.0,WITHDRAWN,القرار الوزاري الموحد,إدارة (اختصاص عام),72.0,829.111,1,1,First Year
164,114028.111,140.111,20111.0,19.111,20111.0,20151.0,2.111,2.0,مقبول,C,NaN,NaN,54.8,1.74,20.0,0.00,0.0,0.0,5.0,13.0,54.8,1.74,7.0,17.0,5.0,13.0,2.0,4.0,5.0,13.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,WITHDRAWN,القرار الوزاري الموحد,إدارة الأعمال,148.0,236.111,1,1,First Year
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188468,412612.111,33276.111,20252.0,50.111,20251.0,20252.0,3.111,9.0,منسحب,C,0.98,39.6,0.0,0.00,39.6,0.98,3.0,8.0,3.0,8.0,39.6,0.98,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,5.0,15.0,3.0,8.0,2.0,7.0,1.0,WITHDRAWN,القرار رقم 230,إجازة في هندسة البترول2023,180.0,1987.111,1,1,First Year
188705,403758.111,33368.111,20251.0,40.111,20251.0,20252.0,3.111,2.0,مقبول,C,NaN,NaN,36.0,0.80,0.0,0.00,0.0,0.0,2.0,5.0,36.0,0.80,5.0,14.0,2.0,5.0,2.0,6.0,2.0,5.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,WITHDRAWN,القرار رقم 230,العلوم الإدارية (اختصاص عام) 2023,72.0,2035.111,1,1,First Year
188706,412079.111,33368.111,20252.0,40.111,20251.0,20252.0,3.111,9.0,منسحب,C,0.80,36.0,0.0,0.00,36.0,0.80,2.0,5.0,2.0,5.0,36.0,0.80,4.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,5.0,14.0,2.0,5.0,2.0,6.0,2.0,WITHDRAWN,القرار رقم 230,العلوم الإدارية (اختصاص عام) 2023,72.0,2035.111,1,1,First Year
188912,403886.111,33484.111,20252.0,42.111,20252.0,20252.0,3.111,9.0,منسحب,C,NaN,NaN,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,WITHDRAWN,القرار رقم 230,إجازة دكتور في طب الأسنان 2023,185.0,1981.111,1,1,First Year
188913,403885.111,33486.111,20252.0,42.111,20252.0,20252.0,3.111,9.0,منسحب,C,NaN,NaN,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,WITHDRAWN,القرار رقم 230,إجازة دكتور في طب الأسنان 2023,185.0,1981.111,1,1,First Year

In [9]:
df1=pd.read_parquet(r"D:\AI\Real projects\Academic_Advisor_Simple\student_over_polict_unresolved.parquet")

In [20]:
df1

,student_course_id,student_id,course_id,part_id,grade_id,final_mark,points,finish_status_course,course_name_sl,register_status,in_credits,in_gpa,in_agpa,study_mode_course,degree_id,student_name_sl,degree_name_sl_course,faculty_id,course_credits,active,student_status_id,start_part_id,finish_part_id,grade_version_id,permanent_status_id,permanent_status_sl,study_mode_status,prev_gpa_points,prev_gpa_percent,gpa_percent,gpa_points,start_agpa_percent,start_agpa_points,start_total_in_courses,start_total_in_credits,end_total_in_courses,end_total_in_credits,end_agpa_percent,end_agpa_points,semester_reg_courses,semester_reg_credits,semester_pass_courses,semester_pass_credits,semester_fail_courses,semester_fail_credits,semester_in_courses,semester_in_credits,total_semesters,total_reg_courses,total_reg_credits,total_pass_courses,total_pass_credits,total_fail_courses,total_fail_credits,reg_total_semesters,finish_status_status,version_title_sl,degree_name_sl_status,degree_credits_count,start_level_id,start_level_name_short,end_level_name_short,start_level_name_pl,course_registered_credits,course_registered_count,source_match,status_row_found,registration_credit_match,registration_count_match,final_year_order,is_final_year_start,remaining_credits_start,registered_all_remaining_credits,reaches_final_year_at_end,classification,exclusion_reason,review_reason
0,4449870.111,30404.111,1424.111,20253,<NA>,NaN,NaN,NaN,اللغة الإنكليزية – 2,R,Y,Y,Y,C,42.111,وائل خالد السليمان,إجازة دكتور في طب الأسنان 2023,3.111,3.0,A,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2,right_only,False,False,<NA>,5,<NA>,NaN,<NA>,<NA>,unresolved,,missing_exact_student_degree_semester_status
1,4449872.111,30404.111,301.111,20253,<NA>,NaN,NaN,NaN,علم الخلية والمناعة,R,Y,Y,Y,C,42.111,وائل خالد السليمان,إجازة دكتور في طب الأسنان 2023,3.111,3.0,A,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2,right_only,False,False,<NA>,5,<NA>,NaN,<NA>,<NA>,unresolved,,missing_exact_student_degree_semester_status
2,4398637.111,30646.111,684.111,20253,<NA>,NaN,NaN,NaN,علم الأنسجة (1),R,Y,Y,Y,C,41.111,ليث عبد الوكاع السيد,دكتور في الطب 2023,2.111,4.0,A,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2,right_only,False,False,<NA>,6,<NA>,NaN,<NA>,<NA>,unresolved,,missing_exact_student_degree_semester_status
3,4398638.111,30646.111,660.111,20253,<NA>,NaN,NaN,NaN,الوراثة,R,Y,Y,Y,C,41.111,ليث عبد الوكاع السيد,دكتور في الطب 2023,2.111,2.0,A,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2,right_only,False,False,<NA>,6,<NA>,NaN,<NA>,<NA>,unresolved,,missing_exact_student_degree_semester_status
4,4397775.111,31416.111,315.111,20253,<NA>,NaN,NaN,NaN,تشريح أسنان (1),R,Y,Y,Y,C,42.111,سميره محمد بيرم العبيد,إجازة دكتور في طب الأسنان 2023,3.111,2.0,A,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,2,right_only,False,False,<NA>,5,<NA>,NaN,<NA>,<NA>,unresolved,,missing_exact_student_degree_semester_status
5,4397776.111,31416.111,329.111,20253,<NA>,NaN,NaN,NaN,علم النسج العام,R,Y,Y,Y,C,42.111,سميره محمد بيرم العبيد,إجازة دكتور في طب الأسنان 2023,3.111,3.0,A,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,2,right_only,False,False,<NA>,5,<NA>,NaN,<NA>,<NA>,unresolved,,missing_exact_student_degree_semester_status
6,4400147.111,31503.111,1181.111,20253,<NA>,NaN,NaN,NaN,البرمجة2,R,Y,Y,Y,C,46.111,صلاح الدين محمد عجاج,الهندسة المعلوماتية/هندسة البرمجيات ونظم المعل...,167.111,3.0,A,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2,right_only,False,False,<NA>,5,<NA>,NaN,<NA>,<NA>,unresolved,,missing_exact_student_degree_semester_status
7,4400148.111,31503.111,1185.111,20253,<NA>,NaN,NaN,NaN,أساسيات قواعد البيانات,R,Y,Y,Y,C,46.111,صلاح الدين محمد عجاج,الهندسة المعلوماتية/هندسة البرمجيات ونظم المعل...,167.111,3.0,A,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2,right_only,False,False,<NA>,5,<NA>,NaN,<NA>,<NA>,unresolved,,missing_exact_student_degree_semester_status
8,4451983.111,31539.111,1183.111,20253,<NA>,NaN,NaN,NaN,بنيان الحواسيب1,R,Y,Y,Y,C,48.111,أحمد ضرار المصري,الهندسة المعلوماتية/هندسة أمن النظم والشبكات ا...,167.111,3.0,A,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,2,right_only,False,False,<NA>,5,<NA>,NaN,<NA>,<NA>,unresolved,,missing_exact_student_degree_semester_status
9,4452457.111,31539.111,1425.111,20253,<NA>,NaN,NaN,NaN,مدخل الى القانون,R,Y,Y,Y,C,48.111,أحمد ضرار المصري,الهندسة المعلوماتية/هندسة أمن النظم والشبكات ا...,167.111,2.0,A,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,2,right_only,False,False,<NA>,5,<NA>,NaN,<NA>,<NA>,unresolved,,missing_exact_student_degree_semester_status

In [11]:
df2=pd.read_parquet(r"D:\AI\Real projects\Academic_Advisor_Simple\student_over_polict.parquet")

In [23]:
df2[df2['part_id']==20253]

,student_course_id,student_id,course_id,part_id,grade_id,final_mark,points,finish_status_course,course_name_sl,register_status,in_credits,in_gpa,in_agpa,study_mode_course,degree_id,student_name_sl,degree_name_sl_course,faculty_id,course_credits,active,student_status_id,start_part_id,finish_part_id,grade_version_id,permanent_status_id,permanent_status_sl,study_mode_status,prev_gpa_points,prev_gpa_percent,gpa_percent,gpa_points,start_agpa_percent,start_agpa_points,start_total_in_courses,start_total_in_credits,end_total_in_courses,end_total_in_credits,end_agpa_percent,end_agpa_points,semester_reg_courses,semester_reg_credits,semester_pass_courses,semester_pass_credits,semester_fail_courses,semester_fail_credits,semester_in_courses,semester_in_credits,total_semesters,total_reg_courses,total_reg_credits,total_pass_courses,total_pass_credits,total_fail_courses,total_fail_credits,reg_total_semesters,finish_status_status,version_title_sl,degree_name_sl_status,degree_credits_count,start_level_id,start_level_name_short,end_level_name_short,start_level_name_pl,course_registered_credits,course_registered_count,source_match,status_row_found,registration_credit_match,registration_count_match,final_year_order,is_final_year_start,remaining_credits_start,registered_all_remaining_credits,reaches_final_year_at_end,classification,exclusion_reason,review_reason
0,4453712.111,10407.111,353.111,20253,<NA>,NaN,NaN,NaN,تعويض الأسنان المتحركة (1),R,Y,Y,Y,C,1.111,بتول احمد جريخ,دكتور في طب الأسنان,3.111,3.0,A,418221.111,20151.0,NaN,3.111,24.0,مفصول من الجامعة - أكاديمياً,C,0.00,0.0,0.0,0.0,53.2,1.66,26.0,66.0,26.0,66.0,53.2,1.66,3.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,34.0,141.0,371.0,38.0,101.0,64.0,166.0,30.0,NaN,القرار رقم 230,دكتور في طب الأسنان,185.0,567.111,3.0,3.0,Third year,8.0,3,both,True,True,True,5,False,119.0,False,False,retained,,
1,4453713.111,10407.111,317.111,20253,<NA>,NaN,NaN,NaN,العلوم السلوكية ومهارات التواصل,R,Y,Y,Y,C,1.111,بتول احمد جريخ,دكتور في طب الأسنان,3.111,2.0,A,418221.111,20151.0,NaN,3.111,24.0,مفصول من الجامعة - أكاديمياً,C,0.00,0.0,0.0,0.0,53.2,1.66,26.0,66.0,26.0,66.0,53.2,1.66,3.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,34.0,141.0,371.0,38.0,101.0,64.0,166.0,30.0,NaN,القرار رقم 230,دكتور في طب الأسنان,185.0,567.111,3.0,3.0,Third year,8.0,3,both,True,True,True,5,False,119.0,False,False,retained,,
2,4453716.111,10407.111,330.111,20253,<NA>,NaN,NaN,NaN,التشريح المرضي العام,R,Y,Y,Y,C,1.111,بتول احمد جريخ,دكتور في طب الأسنان,3.111,3.0,A,418221.111,20151.0,NaN,3.111,24.0,مفصول من الجامعة - أكاديمياً,C,0.00,0.0,0.0,0.0,53.2,1.66,26.0,66.0,26.0,66.0,53.2,1.66,3.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,34.0,141.0,371.0,38.0,101.0,64.0,166.0,30.0,NaN,القرار رقم 230,دكتور في طب الأسنان,185.0,567.111,3.0,3.0,Third year,8.0,3,both,True,True,True,5,False,119.0,False,False,retained,,
3,4449457.111,10707.111,365.111,20253,986.111,0.0,0.0,W,مداواة الأسنان اللبية (3),R,Y,N,N,C,1.111,عبد الرحمن رمضان سيد,دكتور في طب الأسنان,3.111,3.0,A,418036.111,20161.0,NaN,3.111,2.0,مقبول,C,1.08,41.6,0.0,0.0,60.0,2.00,47.0,118.0,47.0,118.0,60.0,2.00,3.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,28.0,116.0,297.0,61.0,158.0,47.0,117.0,27.0,NaN,القرار رقم 230,دكتور في طب الأسنان,185.0,568.111,4.0,4.0,Fourth Year,7.0,3,both,True,True,True,5,False,67.0,False,False,retained,,
4,4449459.111,10707.111,336.111,20253,<NA>,NaN,NaN,NaN,علم النسج حول السنية (2),R,Y,Y,Y,C,1.111,عبد الرحمن رمضان سيد,دكتور في طب الأسنان,3.111,2.0,A,418036.111,20161.0,NaN,3.111,2.0,مقبول,C,1.08,41.6,0.0,0.0,60.0,2.00,47.0,118.0,47.0,118.0,60.0,2.00,3.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,28.0,116.0,297.0,61.0,158.0,47.0,117.0,27.0,NaN,القرار رقم 230,دكتور في طب الأسنان,185.0,568.111,4.0,4.0,Fourth Year,7.0,3,both,True,True,True,5,False,67.0,False,False,retained,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7021,4414664.111,9890.111,331.111,20253,<NA>,NaN,NaN,NaN,علم النسج الخاص بالفم والأسنان,R,Y,Y,Y,C,1.111,وسيم شمس الدين حوريه,دكتور في طب الأسنان,3.111,3.0,A,415621.111,20151.0,NaN,3.111,31.0,مفصول - استدراكي,C,2.04,60.8,0.0,0.0,58.8,1.94,43.0,107.0,43.0,107.0,58.8,1.94,2.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,30.0,121.0,287.0,59.0,149.0,53.0,117.0,25.0,NaN,القرار رقم 230,دكتور في طب الأسنان,185.0,568.111,4.0,4.0,Fourth Year,5.0,2,both,True,True,True,5,False,78.0,False,False,retained,,
7022,4414665.111,9890.111,1020.111,20253,<NA>,NaN,NaN,NaN,علم الإدارة,R,Y,Y,Y,C,1.111,وسيم شمس الدين حوريه,دكتور في طب الأسنان,3.111,2.0,A,415621.111,20151.0,NaN,3.111,31.0,مفصول - استدراكي,C,2.04,60.8,0.0,0.0,58.8,1.94,43.0,107.0,43.0,107.0,58.8,1.94,2.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,30.0,121.0,287.0,59.0,149.0,53.0,117.0,25.0,NaN,القرار رقم 230,دكتور في طب الأسنان,185.0,568.111,4.0,4.0,Fourth Year,5.0,2,both,True,True,True,5,False,78.0,False,False,retained,,
7023,4449981.111,9915.111,698.111,20253,<NA>,NaN,NaN,NaN,الطب الباطني (4),R,Y,Y,Y,C,2.111,نوال حمادي الخاني,دكتور في الطب,2.111,6.0,A,417852.111,20151.0,NaN,3.111,31.0,مفصول - استدراكي,C,0.00,0.0,0.0,0.0,53.8,1.69,37.0,124.0,37.0,124.0,53.8,1.69,1.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,32.0,116.0,396.5,48.0,156.0,62.0,220.5,28.0,NaN,القرار رقم 230,دكتور في الطب,251.0,555.111,4.0,4.0,Fourth Year,6.0,1,both,True,True,True,6,False,127.0,False,False,retained,,
7024,4447477.111,9924.111,308.111,20253,<NA>,NaN,NaN,NaN,الإسعافات الأولية,R,Y,Y,Y,C,1.111,فيصل سالم المشوح,دكتور في طب الأسنان,3.111,2.0,A,417888.111,20151.0,NaN,3.111,24.0,مفصول من الجامعة - أكاديمياً,C,0.00,0.0,0.0,0.0,58.0,1.90,38.0,93.0,38.0,93.0,58.0,1.90,2.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,30.0,135.0,320.0,48.0,119.0,55.0,134.0,29.0,NaN,القرار رقم 230,دكتور في طب الأسنان,185.0,567.111,3.0,3.0,Third year,4.0,2,both,True,True,True,5,False,92.0,False,False,retained,,
7025,4447495.111,9924.111,321.111,20253,<NA>,NaN,NaN,NaN,مقدمة في طب الأسنان السريري,R,Y,Y,Y,C,1.111,فيصل سالم المشوح,دكتور في طب الأسنان,3.111,2.0,A,417888.111,20151.0,NaN,3.111,24.0,مفصول من الجامعة - أكاديمياً,C,0.00,0.0,0.0,0.0,58.0,1.90,38.0,93.0,38.0,93.0,58.0,1.90,2.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,30.0,135.0,320.0,48.0,119.0,55.0,134.0,29.0,NaN,القرار رقم 230,دكتور في طب الأسنان,185.0,567.111,3.0,3.0,Third year,4.0,2,both,True,True,True,5,False,92.0,False,False,retained,,

In [24]:
df3=pd.read_parquet(r"D:\AI\Real projects\Academic_Advisor_Simple\student_under_12_after_status_change.parquet")

In [25]:
df3

,student_course_id,student_id,course_id,part_id,grade_id,final_mark,points,finish_status_course,course_name_sl,register_status,in_credits,in_gpa,in_agpa,study_mode_course,degree_id,student_name_sl,degree_name_sl_course,faculty_id,course_credits,active,is_pass_fail,is_known_non_pass_fail,is_missing_finish_status,finish_status_code_for_audit,finish_status_name_for_audit,pass_fail_course_credits,known_non_pass_fail_course_credits,missing_finish_status_course_credits,student_status_id,start_part_id,finish_part_id,grade_version_id,permanent_status_id,permanent_status_sl,study_mode_status,prev_gpa_points,prev_gpa_percent,gpa_percent,gpa_points,start_agpa_percent,start_agpa_points,start_total_in_courses,start_total_in_credits,end_total_in_courses,end_total_in_credits,end_agpa_percent,end_agpa_points,semester_reg_courses,semester_reg_credits,semester_pass_courses,semester_pass_credits,semester_fail_courses,semester_fail_credits,semester_in_courses,semester_in_credits,total_semesters,total_reg_courses,total_reg_credits,total_pass_courses,total_pass_credits,total_fail_courses,total_fail_credits,reg_total_semesters,finish_status_status,version_title_sl,degree_name_sl_status,degree_credits_count,start_level_id,start_level_name_short,end_level_name_short,start_level_name_pl,course_registered_credits,course_registered_count,pass_fail_credits,known_non_pass_fail_credits,missing_finish_status_credits,missing_finish_status_courses,source_match,registered_credits_before_filter,non_pass_fail_credits,status_row_found,registration_credit_match,registration_count_match,credits_after_known_status_exclusions,known_statuses_suffice_for_below_12,status_pass_fail_credits,status_pass_fail_matches_course_codes,final_year_order,is_final_year_start,remaining_credits_start,registered_all_remaining_credits,classification,reason
0,3591668.111,10238.111,992.111,20251,992.111,2.0,0.00,Z,صيدلة صناعية,R,Y,Y,Y,C,13.111,محمد يمان محمد محي الدين بني المرجه,الصيدلة و الكيمياء الصيدلية,4.111,3.0,A,False,True,False,Z,محروم من الامتحان,0.0,3.0,0.0,400188.111,20151.0,NaN,3.111,24.0,مفصول من الجامعة - أكاديمياً,C,0.00,0.0,0.0,0.00,57.4,1.87,38.0,98.0,38.0,98.0,57.4,1.87,5.0,13.0,0.0,0.0,5.0,13.0,0.0,0.0,30.0,122.0,324.0,46.0,117.0,66.0,178.0,29.0,NaN,القرار رقم 230,الصيدلة و الكيمياء الصيدلية,178.0,616.111,4.0,4.0,Fourth Year,13.0,5,0.0,13.0,0.0,0.0,both,13.0,13.0,True,True,True,0.0,True,13.0,False,5,False,80.0,False,retained,known_non_pass_fail_statuses_reduce_filtered_c...
1,3591669.111,10238.111,1000.111,20251,992.111,1.0,0.00,Z,كيمياء حيوية سريرية,R,Y,Y,Y,C,13.111,محمد يمان محمد محي الدين بني المرجه,الصيدلة و الكيمياء الصيدلية,4.111,3.0,A,False,True,False,Z,محروم من الامتحان,0.0,3.0,0.0,400188.111,20151.0,NaN,3.111,24.0,مفصول من الجامعة - أكاديمياً,C,0.00,0.0,0.0,0.00,57.4,1.87,38.0,98.0,38.0,98.0,57.4,1.87,5.0,13.0,0.0,0.0,5.0,13.0,0.0,0.0,30.0,122.0,324.0,46.0,117.0,66.0,178.0,29.0,NaN,القرار رقم 230,الصيدلة و الكيمياء الصيدلية,178.0,616.111,4.0,4.0,Fourth Year,13.0,5,0.0,13.0,0.0,0.0,both,13.0,13.0,True,True,True,0.0,True,13.0,False,5,False,80.0,False,retained,known_non_pass_fail_statuses_reduce_filtered_c...
2,3591670.111,10238.111,1012.111,20251,992.111,0.0,0.00,Z,مهارات تواصل,R,Y,Y,Y,C,13.111,محمد يمان محمد محي الدين بني المرجه,الصيدلة و الكيمياء الصيدلية,4.111,2.0,A,False,True,False,Z,محروم من الامتحان,0.0,2.0,0.0,400188.111,20151.0,NaN,3.111,24.0,مفصول من الجامعة - أكاديمياً,C,0.00,0.0,0.0,0.00,57.4,1.87,38.0,98.0,38.0,98.0,57.4,1.87,5.0,13.0,0.0,0.0,5.0,13.0,0.0,0.0,30.0,122.0,324.0,46.0,117.0,66.0,178.0,29.0,NaN,القرار رقم 230,الصيدلة و الكيمياء الصيدلية,178.0,616.111,4.0,4.0,Fourth Year,13.0,5,0.0,13.0,0.0,0.0,both,13.0,13.0,True,True,True,0.0,True,13.0,False,5,False,80.0,False,retained,known_non_pass_fail_statuses_reduce_filtered_c...
3,3591671.111,10238.111,985.111,20251,992.111,0.0,0.00,Z,تحليل آلي,R,Y,Y,Y,C,13.111,محمد يمان محمد محي الدين بني المرجه,الصيدلة و الكيمياء الصيدلية,4.111,3.0,A,False,True,False,Z,محروم من الامتحان,0.0,3.0,0.0,400188.111,20151.0,NaN,3.111,24.0,مفصول من الجامعة - أكاديمياً,C,0.00,0.0,0.0,0.00,57.4,1.87,38.0,98.0,38.0,98.0,57.4,1.87,5.0,13.0,0.0,0.0,5.0,13.0,0.0,0.0,30.0,122.0,324.0,46.0,117.0,66.0,178.0,29.0,NaN,القرار رقم 230,الصيدلة و الكيمياء الصيدلية,178.0,616.111,4.0,4.0,Fourth Year,13.0,5,0.0,13.0,0.0,0.0,both,13.0,13.0,True,True,True,0.0,True,13.0,False,5,False,80.0,False,retained,known_non_pass_fail_statuses_reduce_filtered_c...
4,3591672.111,10238.111,980.111,20251,992.111,0.0,0.00,Z,علم الأدوية 1,R,Y,Y,Y,C,13.111,محمد يمان محمد محي الدين بني المرجه,الصيدلة و الكيمياء الصيدلية,4.111,2.0,A,False,True,False,Z,محروم من الامتحان,0.0,2.0,0.0,400188.111,20151.0,NaN,3.111,24.0,مفصول من الجامعة - أكاديمياً,C,0.00,0.0,0.0,0.00,57.4,1.87,38.0,98.0,38.0,98.0,57.4,1.87,5.0,13.0,0.0,0.0,5.0,13.0,0.0,0.0,30.0,122.0,324.0,46.0,117.0,66.0,178.0,29.0,NaN,القرار رقم 230,الصيدلة و الكيمياء الصيدلية,178.0,616.111,4.0,4.0,Fourth Year,13.0,5,0.0,13.0,0.0,0.0,both,13.0,13.0,True,True,True,0.0,True,13.0,False,5,False,80.0,False,retained,known_non_pass_fail_statuses_reduce_filtered_c...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5743,3689449.111,9976.111,333.111,20252,984.111,50.0,1.50,P,طب الفم (1),R,Y,Y,Y,C,1.111,ساري علي أسعد,دكتور في طب الأسنان,3.111,2.0,A,True,False,False,P,امتياز | جيد | جيد جداً | شرف | مقبول | ممتاز ...,2.0,0.0,0.0,405103.111,20151.0,NaN,3.111,24.0,مفصول من الجامعة - أكاديمياً,C,0.71,34.2,32.6,0.63,58.0,1.90,53.0,124.0,56.0,130.0,57.4,1.87,7.0,15.0,3.0,6.0,4.0,9.0,3.0,6.0,32.0,145.0,336.0,73.0,176.0,45.0,96.0,32.0,NaN,القرار رقم 230,دكتور في طب الأسنان,185.0,568.111,4.0,5.0,Fourth Year,15.0,7,7.0,8.0,0.0,0.0,both,15.0,8.0,True,True,True,7.0,True,15.0,False,5,False,61.0,False,retained,known_non_pass_fail_statuses_reduce_filtered_c...
5744,3689450.111,9976.111,331.111,20252,992.111,6.0,0.00,Z,علم النسج الخاص بالفم والأسنان,R,Y,Y,Y,C,1.111,ساري علي أسعد,دكتور في طب الأسنان,3.111,3.0,A,False,True,False,Z,محروم من الامتحان,0.0,3.0,0.0,405103.111,20151.0,NaN,3.111,24.0,مفصول من الجامعة - أكاديمياً,C,0.71,34.2,32.6,0.63,58.0,1.90,53.0,124.0,56.0,130.0,57.4,1.87,7.0,15.0,3.0,6.0,4.0,9.0,3.0,6.0,32.0,145.0,336.0,73.0,176.0,45.0,96.0,32.0,NaN,القرار رقم 230,دكتور في طب الأسنان,185.0,568.111,4.0,5.0,Fourth Year,15.0,7,7.0,8.0,0.0,0.0,both,15.0,8.0,True,True,True,7.0,True,15.0,False,5,False,61.0,False,retained,known_non_pass_fail_statuses_reduce_filtered_c...
5745,3689451.111,9976.111,1033.111,20252,983.111,57.0,1.75,P,مبادئ السيطرة على الألم و القلق,R,Y,Y,Y,C,1.111,ساري علي أسعد,دكتور في طب الأسنان,3.111,2.0,A,True,False,False,P,امتياز | جيد | جيد جداً | شرف | مقبول | ممتاز ...,2.0,0.0,0.0,405103.111,20151.0,NaN,3.111,24.0,مفصول من الجامعة - أكاديمياً,C,0.71,34.2,32.6,0.63,58.0,1.90,53.0,124.0,56.0,130.0,57.4,1.87,7.0,15.0,3.0,6.0,4.0,9.0,3.0,6.0,32.0,145.0,336.0,73.0,176.0,45.0,96.0,32.0,NaN,القرار رقم 230,دكتور في طب الأسنان,185.0,568.111,4.0,5.0,Fourth Year,15.0,7,7.0,8.0,0.0,0.0,both,15.0,8.0,True,True,True,7.0,True,15.0,False,5,False,61.0,False,retained,known_non_pass_fail_statuses_reduce_filtered_c...
5746,3689452.111,9976.111,360.111,20252,992.111,10.0,0.00,Z,مداواة أسنان ترميمية (3),R,Y,Y,Y,C,1.111,ساري علي أسعد,دكتور في طب الأسنان,3.111,3.0,A,False,True,False,Z,محروم من الامتحان,0.0,3.0,0.0,405103.111,20151.0,NaN,3.111,24.0,مفصول من الجامعة - أكاديمياً,C,0.71,34.2,32.6,0.63,58.0,1.90,53.0,124.0,56.0,130.0,57.4,1.87,7.0,15.0,3.0,6.0,4.0,9.0,3.0,6.0,32.0,145.0,336.0,73.0,176.0,45.0,96.0,32.0,NaN,القرار رقم 230,دكتور في طب الأسنان,185.0,568.111,4.0,5.0,Fourth Year,15.0,7,7.0,8.0,0.0,0.0,both,15.0,8.0,True,True,True,7.0,True,15.0,False,5,False,61.0,False,retained,known_non_pass_fail_statuses_reduce_filtered_c...
5747,3689453.111,9976.111,318.111,20252,985.111,32.0,0.00,F,مكافحة العدوى,R,Y,Y,Y,C,1.111,ساري علي أسعد,دكتور في طب الأسنان,3.111,1.0,A,True,False,False,F,رسوب,1.0,0.0,0.0,405103.111,20151.0,NaN,3.111,24.0,مفصول من الجامعة - أكاديمياً,C,0.71,34.2,32.6,0.63,58.0,1.90,53.0,124.0,56.0,130.0,57.4,1.87,7.0,15.0,3.0,6.0,4.0,9.0,3.0,6.0,32.0,145.0,336.0,73.0,176.0,45.0,96.0,32.0,NaN,القرار رقم 230,دكتور في طب الأسنان,185.0,568.111,4.0,5.0,Fourth Year,15.0,7,7.0,8.0,0.0,0.0,both,15.0,8.0,True,True,True,7.0,True,15.0,False,5,False,61.0,False,retained,known_non_pass_fail_statuses_reduce_filtered_c...