In [3]:
import pandas as pd 
PLAN_GPA_EVALUATION_PATH='D:\AI\Real projects\Academic_Advisor_Simple\data\evaluation\plan_gpa_evaluation_2025.parquet'
df=pd.read_parquet(PLAN_GPA_EVALUATION_PATH)

In [4]:
pd.set_option('display.max_columns',100)

In [22]:
df.describe()

,part_id,course_count,total_credits,actual_quality_points,predicted_quality_points,source_semester_gpa,actual_plan_gpa,predicted_plan_gpa,plan_gpa_error,plan_gpa_absolute_error,quality_points_error,formula_vs_source_gpa_error
count,12976.0,12976.0,12976.0,12976.0,12976.0,12976.0,12976.0,12976.0,12976.0,12976.0,12976.0,12976.0
mean,20251.49106,5.284988,15.864904,36.54411,38.834839,2.219103,2.233613,2.393266,0.159652,0.376375,2.290729,0.01451
std,0.499939,1.603659,4.466762,17.618337,16.174474,0.836297,0.823615,0.643141,0.503751,0.370927,7.019666,0.106684
min,20251.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,-2.8125,0.0,-47.25,-0.075385
25%,20251.0,5.0,14.0,24.0,28.9375,1.72,1.75,2.044118,-0.140795,0.125,-2.125,-0.0025
50%,20251.0,6.0,17.0,37.75,40.0625,2.35,2.353554,2.5,0.107143,0.267857,1.5,0.0
75%,20252.0,6.0,18.0,49.0,49.5,2.8325,2.838235,2.833333,0.407895,0.5,6.0,0.002174
max,20252.0,10.0,39.0,102.0,93.75,4.0,4.0,3.666667,3.0,3.0,54.0,3.5

In [ ]:
a=df[df['actual_quality_points']==0]

In [21]:
a

,student_id,degree_id,part_id,course_count,total_credits,actual_quality_points,predicted_quality_points,source_semester_gpa,actual_plan_gpa,predicted_plan_gpa,plan_gpa_error,plan_gpa_absolute_error,quality_points_error,formula_vs_source_gpa_error
0,14026.111,2.111,20252,1,3.0,0.0,9.0,0.0,0.0,3.0,3.0,3.0,9.0,0.0
1,16323.111,2.111,20252,1,3.0,0.0,9.0,0.0,0.0,3.0,3.0,3.0,9.0,0.0
2,17629.111,2.111,20252,1,3.0,0.0,9.0,0.0,0.0,3.0,3.0,3.0,9.0,0.0
3,24339.111,11.111,20252,4,12.0,0.0,36.0,0.0,0.0,3.0,3.0,3.0,36.0,0.0
5,14861.111,11.111,20251,1,4.0,0.0,11.0,0.0,0.0,2.75,2.75,2.75,11.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12961,33193.111,61.111,20252,3,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12967,33478.111,50.111,20252,3,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12971,33693.111,64.111,20252,2,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12974,9817.111,2.111,20252,1,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12975,9878.111,13.111,20252,1,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [19]:
a['course_count'].value_counts()

course_count
4    60
5    43
1    38
3    33
6    23
2    20
7     1
Name: count, dtype: Int64

In [12]:
df['course_count'].value_counts()

course_count
6     4382
5     3322
4     1556
7     1556
1      585
3      584
8      470
2      322
9      171
10      28
Name: count, dtype: Int64

In [21]:
a=df[(df['part_id']==20251)&(df['end_level_name_short']=='3')]

In [23]:
a[a['student_id']=='33330.111']

,student_course_id,student_id,course_id,part_id,grade_id,final_mark,points,course_name_sl,degree_id,degree_name_sl_course,faculty_id,course_credits,course_outcome_status,attempt_number,student_status_id,degree_name_sl_status,start_part_id,finish_part_id,grade_version_id,prev_gpa_points,last_enrolled_gpa,observed_gap_semesters,gpa_points,start_agpa_points,start_total_in_courses,start_total_in_credits,end_total_in_courses,end_total_in_credits,end_agpa_points,semester_reg_courses,semester_reg_credits,semester_pass_courses,semester_pass_credits,semester_fail_courses,semester_fail_credits,total_semesters,total_reg_courses,total_reg_credits,total_pass_courses,total_pass_credits,total_fail_courses,total_fail_credits,reg_total_semesters,finish_status,degree_credits_count,start_level_name_short,end_level_name_short,plan_degree_course_id,plan_course_type_id,plan_requirement_type_id,plan_requirement_type_sl,plan_course_name_sl,plan_course_official_sl,plan_degree_name_sl,plan_year_order,plan_semester_order,plan_course_credits,plan_credits_count,plan_active,plan_match,diploma_gpa,diploma_type_id
420779,3632886.111,33330.111,1421.111,20251,979.111,75,2.75,مهارات اللغة العربية,41.111,دكتور في الطب 2023,2.111,2.0,pass,1,403720.111,دكتور في الطب 2023,20251,<NA>,3.111,<NA>,<NA>,<NA>,3.29,0.0,0,0.0,28,96.0,3.29,7,15.0,6,13.0,0,0.0,1,0,0.0,0,0.0,0,0.0,1,<NA>,251.0,3,3,2453.111,1,1,متطلبات الجامعة الإجبارية,مهارات اللغة العربية,مهارات اللغة العربية,دكتور في الطب 2023,1,1,2.0,11.0,A,True,99.6,15.111
420780,3632891.111,33330.111,1424.111,20251,975.111,96,3.75,اللغة الإنكليزية – 2,41.111,دكتور في الطب 2023,2.111,3.0,pass,1,403720.111,دكتور في الطب 2023,20251,<NA>,3.111,<NA>,<NA>,<NA>,3.29,0.0,0,0.0,28,96.0,3.29,7,15.0,6,13.0,0,0.0,1,0,0.0,0,0.0,0,0.0,1,<NA>,251.0,3,3,2456.111,1,1,متطلبات الجامعة الإجبارية,اللغة الإنكليزية – 2,اللغة الإنكليزية – 2,دكتور في الطب 2023,1,2,3.0,11.0,A,True,99.6,15.111
420781,3632888.111,33330.111,1429.111,20251,976.111,91,3.5,علم البيئة,41.111,دكتور في الطب 2023,2.111,2.0,pass,1,403720.111,دكتور في الطب 2023,20251,<NA>,3.111,<NA>,<NA>,<NA>,3.29,0.0,0,0.0,28,96.0,3.29,7,15.0,6,13.0,0,0.0,1,0,0.0,0,0.0,0,0.0,1,<NA>,251.0,3,3,2461.111,1,2,متطلبات الجامعة الاختيارية,علم البيئة,علم البيئة,دكتور في الطب 2023,1,1,2.0,4.0,A,True,99.6,15.111
420782,3632890.111,33330.111,1436.111,20251,975.111,97,3.75,المهارات الحركية البدنية والذهنية,41.111,دكتور في الطب 2023,2.111,2.0,pass,1,403720.111,دكتور في الطب 2023,20251,<NA>,3.111,<NA>,<NA>,<NA>,3.29,0.0,0,0.0,28,96.0,3.29,7,15.0,6,13.0,0,0.0,1,0,0.0,0,0.0,0,0.0,1,<NA>,251.0,3,3,2468.111,1,2,متطلبات الجامعة الاختيارية,المهارات الحركية البدنية والذهنية,المهارات الحركية البدنية والذهنية,دكتور في الطب 2023,3,1,2.0,4.0,A,True,99.6,15.111
420783,3633000.111,33330.111,662.111,20251,979.111,75,2.75,مهارات التواصل,41.111,دكتور في الطب 2023,2.111,2.0,pass,1,403720.111,دكتور في الطب 2023,20251,<NA>,3.111,<NA>,<NA>,<NA>,3.29,0.0,0,0.0,28,96.0,3.29,7,15.0,6,13.0,0,0.0,1,0,0.0,0,0.0,0,0.0,1,<NA>,251.0,3,3,2475.111,1,3,متطلبات الكلية الإجبارية,مهارات التواصل,مهارات التواصل,دكتور في الطب 2023,3,2,2.0,22.0,A,True,99.6,15.111
420785,3632999.111,33330.111,691.111,20251,978.111,84,3.0,علم المناعة,41.111,دكتور في الطب 2023,2.111,2.0,pass,1,403720.111,دكتور في الطب 2023,20251,<NA>,3.111,<NA>,<NA>,<NA>,3.29,0.0,0,0.0,28,96.0,3.29,7,15.0,6,13.0,0,0.0,1,0,0.0,0,0.0,0,0.0,1,<NA>,251.0,3,3,2408.111,1,5,متطلبات الشهادة الإجبارية,علم المناعة,علم المناعة,دكتور في الطب 2023,3,2,2.0,210.0,A,True,99.6,15.111

In [8]:
df['observed_gap_semesters'].value_counts(dropna=False)

observed_gap_semesters
0       364871
<NA>     65839
1         3101
2          357
Name: count, dtype: Int64

10815.111
3472.111
3470.111

In [9]:
df[df['total_fail_credits']==713.5]

Empty DataFrame
Columns: [student_course_id, student_id, course_id, part_id, grade_id, final_mark, points, course_name_sl, degree_id, degree_name_sl_course, faculty_id, course_credits, course_outcome_status, attempt_number, student_status_id, degree_name_sl_status, start_part_id, finish_part_id, grade_version_id, prev_gpa_points, last_enrolled_gpa, observed_gap_semesters, gpa_points, start_agpa_points, start_total_in_courses, start_total_in_credits, end_total_in_courses, end_total_in_credits, end_agpa_points, semester_reg_courses, semester_reg_credits, semester_pass_courses, semester_pass_credits, semester_fail_courses, semester_fail_credits, total_semesters, total_reg_courses, total_reg_credits, total_pass_courses, total_pass_credits, total_fail_courses, total_fail_credits, reg_total_semesters, finish_status, degree_credits_count, start_level_name_short, end_level_name_short, plan_degree_course_id, plan_course_type_id, plan_requirement_type_id, plan_requirement_type_sl, plan_course_name_sl, plan_course_official_sl, plan_degree_name_sl, plan_year_order, plan_semester_order, plan_course_credits, plan_credits_count, plan_active, plan_match, diploma_gpa, diploma_type_id]
Index: []

In [10]:
df.describe()

,part_id,final_mark,points,course_credits,attempt_number,start_part_id,finish_part_id,prev_gpa_points,last_enrolled_gpa,observed_gap_semesters,gpa_points,start_agpa_points,start_total_in_courses,start_total_in_credits,end_total_in_courses,end_total_in_credits,end_agpa_points,semester_reg_courses,semester_reg_credits,semester_pass_courses,semester_pass_credits,semester_fail_courses,semester_fail_credits,total_semesters,total_reg_courses,total_reg_credits,total_pass_courses,total_pass_credits,total_fail_courses,total_fail_credits,reg_total_semesters,degree_credits_count,plan_year_order,plan_semester_order,plan_course_credits,plan_credits_count,diploma_gpa,diploma_type_id
count,434168.0,434168.0,434168.0,434168.0,434168.0,434168.0,185640.0,390518.0,390064.0,368329.0,434168.0,434168.0,434168.0,434168.0,434168.0,434168.0,434168.0,434168.0,434168.0,434168.0,434168.0,434168.0,434168.0,434168.0,434168.0,434168.0,434168.0,434168.0,434168.0,434168.0,434168.0,434168.0,434026.0,434026.0,434101.0,434101.0,434143.0,434143.0
mean,20227.15055,70.450828,2.344814,2.887054,1.10873,20203.96303,20233.60049,2.277483,2.294444,0.010358,2.318545,1.971157,27.965829,77.511356,33.208991,92.13796,2.441652,5.813743,16.177587,5.121156,14.226069,0.492558,1.402868,7.966573,34.354427,95.846375,28.279196,78.710673,4.269357,12.158643,7.804007,185.690067,2.738601,1.495818,2.887113,110.482411,86.068943,16.158139
std,16.518425,15.756603,0.960199,1.372057,0.386409,25.580928,13.069088,0.823792,0.801526,0.110403,0.726967,1.051079,20.228931,56.068829,20.471288,56.527012,0.512112,1.59218,4.194315,1.906796,5.172246,0.932017,2.732128,5.535791,26.212514,72.927957,20.568182,57.063382,7.99068,22.687407,5.364761,39.446965,1.425654,0.499983,1.372132,71.403233,11.581446,6.179861
min,20201.0,0.0,0.0,0.0,1.0,20111.0,20132.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,72.0,1.0,1.0,0.0,4.0,8.57,13.111
25%,20212.0,61.0,2.0,2.0,1.0,20191.0,20223.0,1.88,1.9,0.0,1.9,1.86,11.0,30.0,15.0,43.0,2.13,5.0,15.0,4.0,11.0,0.0,0.0,4.0,13.0,35.0,11.0,30.0,0.0,0.0,4.0,173.0,1.0,1.0,2.0,48.0,77.5,15.111
50%,20231.0,72.0,2.5,3.0,1.0,20211.0,20233.0,2.41,2.42,0.0,2.41,2.25,26.0,72.0,31.0,87.0,2.42,6.0,17.0,5.0,15.0,0.0,0.0,7.0,31.0,86.0,26.0,73.0,1.0,3.0,7.0,180.0,3.0,1.0,3.0,129.0,89.42,15.111
75%,20242.0,82.0,3.0,3.0,1.0,20221.0,20242.0,2.85,2.85,0.0,2.83,2.66,44.0,121.0,49.0,136.0,2.78,7.0,18.0,6.0,18.0,1.0,2.0,11.0,52.0,145.0,44.0,122.0,5.0,14.0,11.0,185.0,4.0,2.0,3.0,170.0,95.96,15.111
max,20253.0,100.0,4.0,24.0,5.0,20252.0,20252.0,4.0,4.0,2.0,4.0,4.0,81.0,250.0,83.0,255.0,4.0,10.0,39.0,10.0,27.0,6.0,24.0,38.0,169.0,499.5,87.0,275.0,95.0,277.0,36.0,251.0,6.0,2.0,24.0,210.0,100.0,55.111

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 434168 entries, 0 to 434167
Data columns (total 62 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   student_course_id         434168 non-null  string
 1   student_id                434168 non-null  string
 2   course_id                 434168 non-null  string
 3   part_id                   434168 non-null  Int64
 4   grade_id                  434168 non-null  string
 5   final_mark                434168 non-null  Int64
 6   points                    434168 non-null  Float64
 7   course_name_sl            434168 non-null  string
 8   degree_id                 434168 non-null  string
 9   degree_name_sl_course     434168 non-null  string
 10  faculty_id                434168 non-null  string
 11  course_credits            434168 non-null  Float64
 12  course_outcome_status     434168 non-null  str
 13  attempt_number            434168 non-null  Int64
 14  student_status_id         434168 non-null  string
 15  degree_name_sl_status     434168 non-null  string
 16  start_part_id             434168 non-null  Int64
 17  finish_part_id            185640 non-null  Int64
 18  grade_version_id          434168 non-null  string
 19  prev_gpa_points           390518 non-null  Float64
 20  last_enrolled_gpa         390064 non-null  Float64
 21  observed_gap_semesters    368329 non-null  Int64
 22  gpa_points                434168 non-null  Float64
 23  start_agpa_points         434168 non-null  Float64
 24  start_total_in_courses    434168 non-null  Int64
 25  start_total_in_credits    434168 non-null  Float64
 26  end_total_in_courses      434168 non-null  Int64
 27  end_total_in_credits      434168 non-null  Float64
 28  end_agpa_points           434168 non-null  Float64
 29  semester_reg_courses      434168 non-null  Int64
 30  semester_reg_credits      434168 non-null  Float64
 31  semester_pass_courses     434168 non-null  Int64
 32  semester_pass_credits     434168 non-null  Float64
 33  semester_fail_courses     434168 non-null  Int64
 34  semester_fail_credits     434168 non-null  Float64
 35  total_semesters           434168 non-null  Int64
 36  total_reg_courses         434168 non-null  Int64
 37  total_reg_credits         434168 non-null  Float64
 38  total_pass_courses        434168 non-null  Int64
 39  total_pass_credits        434168 non-null  Float64
 40  total_fail_courses        434168 non-null  Int64
 41  total_fail_credits        434168 non-null  Float64
 42  reg_total_semesters       434168 non-null  Int64
 43  finish_status             185961 non-null  string
 44  degree_credits_count      434168 non-null  Float64
 45  start_level_name_short    434168 non-null  string
 46  end_level_name_short      434168 non-null  string
 47  plan_degree_course_id     434101 non-null  string
 48  plan_course_type_id       434101 non-null  string
 49  plan_requirement_type_id  434101 non-null  string
 50  plan_requirement_type_sl  434101 non-null  string
 51  plan_course_name_sl       434101 non-null  string
 52  plan_course_official_sl   434101 non-null  string
 53  plan_degree_name_sl       434101 non-null  string
 54  plan_year_order           434026 non-null  Int64
 55  plan_semester_order       434026 non-null  Int64
 56  plan_course_credits       434101 non-null  Float64
 57  plan_credits_count        434101 non-null  Float64
 58  plan_active               434101 non-null  string
 59  plan_match                434168 non-null  bool
 60  diploma_gpa               434143 non-null  Float64
 61  diploma_type_id           434143 non-null  Float64
dtypes: Float64(20), Int64(18), bool(1), str(1), string(22)
memory usage: 368.8 MB