In [1]:
import pandas as pd 
df=pd.read_parquet('d:/AI/Real projects/Academic_Advisor_Simple/data/clean/student_course_enriched.parquet')

In [2]:
pd.set_option('display.max_columns', 100)

In [3]:
df.columns

Index(['student_course_id', 'student_id', 'course_id', 'part_id', 'grade_id',
       'final_mark', 'points', 'course_name_sl', 'degree_id',
       'degree_name_sl_course', 'faculty_id', 'course_credits',
       'course_outcome_status', 'attempt_number', 'student_status_id',
       'degree_name_sl_status', 'start_part_id', 'finish_part_id',
       'grade_version_id', 'prev_gpa_points', 'last_enrolled_gpa',
       'observed_gap_semesters', 'gpa_points', 'start_agpa_points',
       'start_total_in_courses', 'start_total_in_credits',
       'end_total_in_courses', 'end_total_in_credits', 'end_agpa_points',
       'semester_reg_courses', 'semester_reg_credits', 'semester_pass_courses',
       'semester_pass_credits', 'semester_fail_courses',
       'semester_fail_credits', 'total_semesters', 'total_reg_courses',
       'total_reg_credits', 'total_pass_courses', 'total_pass_credits',
       'total_fail_courses', 'total_fail_credits', 'reg_total_semesters',
       'finish_status', 'degree_credits_count', 'start_level_name_short',
       'end_level_name_short', 'plan_degree_course_id', 'plan_course_type_id',
       'plan_requirement_type_id', 'plan_requirement_type_sl',
       'plan_course_name_sl', 'plan_course_official_sl', 'plan_degree_name_sl',
       'plan_year_order', 'plan_semester_order', 'plan_course_credits',
       'plan_credits_count', 'plan_active', 'plan_match'],
      dtype='str')

In [4]:
df

,student_course_id,student_id,course_id,part_id,grade_id,final_mark,points,course_name_sl,degree_id,degree_name_sl_course,faculty_id,course_credits,course_outcome_status,attempt_number,student_status_id,degree_name_sl_status,start_part_id,finish_part_id,grade_version_id,prev_gpa_points,last_enrolled_gpa,observed_gap_semesters,gpa_points,start_agpa_points,start_total_in_courses,start_total_in_credits,end_total_in_courses,end_total_in_credits,end_agpa_points,semester_reg_courses,semester_reg_credits,semester_pass_courses,semester_pass_credits,semester_fail_courses,semester_fail_credits,total_semesters,total_reg_courses,total_reg_credits,total_pass_courses,total_pass_credits,total_fail_courses,total_fail_credits,reg_total_semesters,finish_status,degree_credits_count,start_level_name_short,end_level_name_short,plan_degree_course_id,plan_course_type_id,plan_requirement_type_id,plan_requirement_type_sl,plan_course_name_sl,plan_course_official_sl,plan_degree_name_sl,plan_year_order,plan_semester_order,plan_course_credits,plan_credits_count,plan_active,plan_match
0,1430270.111,10002.111,437.111,20201,983.111,58,1.75,نظرية المعلومات,3.111,هندسة البرمجيات ونظم المعلومات,5.111,3.0,pass,1,290533.111,هندسة البرمجيات ونظم المعلومات,20151,20201,3.111,2.5,2.5,<NA>,2.46,2.25,52,152.0,58,170.0,2.31,6,18.0,6,18.0,0,0.0,15,63,183.0,53,155.0,9,26.0,15,GRADUATED,170.0,5,5,781.111,1,3,متطلبات الكلية الإجبارية,نظرية المعلومات,نظرية المعلومات,هندسة البرمجيات ونظم المعلومات,3,2,3.0,65.0,A,True
1,1430266.111,10002.111,520.111,20201,980.111,73,2.5,الدارات الكهربائية والإلكترونية,3.111,هندسة البرمجيات ونظم المعلومات,5.111,3.0,pass,1,290533.111,هندسة البرمجيات ونظم المعلومات,20151,20201,3.111,2.5,2.5,<NA>,2.46,2.25,52,152.0,58,170.0,2.31,6,18.0,6,18.0,0,0.0,15,63,183.0,53,155.0,9,26.0,15,GRADUATED,170.0,5,5,727.111,3,5,متطلبات الشهادة الإجبارية,الدارات الكهربائية والإلكترونية,الدارات الكهربائية والإلكترونية,هندسة البرمجيات ونظم المعلومات,1,2,3.0,63.0,A,True
2,1430271.111,10002.111,531.111,20201,976.111,90,3.5,مشروع التخرج 2,3.111,هندسة البرمجيات ونظم المعلومات,5.111,3.0,pass,1,290533.111,هندسة البرمجيات ونظم المعلومات,20151,20201,3.111,2.5,2.5,<NA>,2.46,2.25,52,152.0,58,170.0,2.31,6,18.0,6,18.0,0,0.0,15,63,183.0,53,155.0,9,26.0,15,GRADUATED,170.0,5,5,728.111,3,5,متطلبات الشهادة الإجبارية,مشروع التخرج 2,مشروع التخرج 2,هندسة البرمجيات ونظم المعلومات,5,2,3.0,63.0,A,True
3,1430269.111,10002.111,536.111,20201,981.111,66,2.25,نظم الزمن الحقيقي,3.111,هندسة البرمجيات ونظم المعلومات,5.111,3.0,pass,1,290533.111,هندسة البرمجيات ونظم المعلومات,20151,20201,3.111,2.5,2.5,<NA>,2.46,2.25,52,152.0,58,170.0,2.31,6,18.0,6,18.0,0,0.0,15,63,183.0,53,155.0,9,26.0,15,GRADUATED,170.0,5,5,744.111,3,5,متطلبات الشهادة الإجبارية,نظم الزمن الحقيقي,نظم الزمن الحقيقي,هندسة البرمجيات ونظم المعلومات,5,1,3.0,63.0,A,True
4,1430272.111,10002.111,542.111,20201,980.111,71,2.5,أمن الشبكات,3.111,هندسة البرمجيات ونظم المعلومات,5.111,3.0,pass,1,290533.111,هندسة البرمجيات ونظم المعلومات,20151,20201,3.111,2.5,2.5,<NA>,2.46,2.25,52,152.0,58,170.0,2.31,6,18.0,6,18.0,0,0.0,15,63,183.0,53,155.0,9,26.0,15,GRADUATED,170.0,5,5,759.111,3,6,متطلبات الشهادة الاختيارية,أمن الشبكات,أمن الشبكات,هندسة البرمجيات ونظم المعلومات,4,2,3.0,21.0,A,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456448,1612735.111,9998.111,361.111,20211,980.111,71,2.5,مداواة أسنان ترميمية (4),1.111,دكتور في طب الأسنان,3.111,2.0,pass,1,309611.111,دكتور في طب الأسنان,20151,20231,3.111,2.04,2.04,0,1.58,2.05,46,117.0,53,131.0,1.99,9,18.0,7,14.0,2,4.0,21,96,227.0,50,127.0,39,83.0,21,GRADUATED,185.0,4,5,191.111,3,3,متطلبات الكلية الإجبارية,مداواة أسنان ترميمية (4),مداواة أسنان ترميمية (4),دكتور في طب الأسنان,4,2,2.0,170.0,A,True
456449,2010887.111,9998.111,362.111,20212,981.111,67,2.25,مداواة أسنان ترميمية (5),1.111,دكتور في طب الأسنان,3.111,2.0,pass,1,317580.111,دكتور في طب الأسنان,20151,20231,3.111,1.58,1.58,0,2.13,1.99,53,131.0,62,148.0,2.07,10,18.0,9,17.0,1,1.0,22,105,245.0,57,141.0,41,87.0,22,GRADUATED,185.0,5,5,180.111,2,3,متطلبات الكلية الإجبارية,مداواة أسنان ترميمية (5),مداواة أسنان ترميمية (5),دكتور في طب الأسنان,5,2,2.0,170.0,A,True
456450,1407984.111,9998.111,364.111,20201,981.111,67,2.25,مداواة الأسنان اللبية (2),1.111,دكتور في طب الأسنان,3.111,2.0,pass,1,288421.111,دكتور في طب الأسنان,20151,20231,3.111,0.96,0.96,<NA>,1.24,1.97,33,85.0,38,97.0,1.92,8,18.0,5,12.0,3,6.0,18,77,184.0,37,95.0,33,72.0,18,GRADUATED,185.0,3,4,192.111,3,3,متطلبات الكلية الإجبارية,مداواة الأسنان اللبية (2),مداواة الأسنان اللبية (2),دكتور في طب الأسنان,4,2,2.0,170.0,A,True
456451,1545153.111,9998.111,365.111,20203,982.111,64,2.0,مداواة الأسنان اللبية (3),1.111,دكتور في طب الأسنان,3.111,3.0,pass,1,300649.111,دكتور في طب الأسنان,20151,20231,3.111,1.69,1.69,0,2.04,1.98,44,111.0,46,117.0,2.05,3,7.0,2,6.0,1,1.0,20,93,220.0,48,121.0,38,82.0,20,GRADUATED,185.0,4,4,193.111,3,3,متطلبات الكلية الإجبارية,مداواة الأسنان اللبية (3),مداواة الأسنان اللبية (3),دكتور في طب الأسنان,5,1,3.0,170.0,A,True
456452,2010888.111,9998.111,366.111,20212,981.111,68,2.25,مداواة الأسنان اللبية (4),1.111,دكتور في طب الأسنان,3.111,3.0,pass,1,317580.111,دكتور في طب الأسنان,20151,20231,3.111,1.58,1.58,0,2.13,1.99,53,131.0,62,148.0,2.07,10,18.0,9,17.0,1,1.0,22,105,245.0,57,141.0,41,87.0,22,GRADUATED,185.0,5,5,181.111,3,3,متطلبات الكلية الإجبارية,مداواة الأسنان اللبية (4),مداواة الأسنان اللبية (4),دكتور في طب الأسنان,5,2,3.0,170.0,A,True

In [5]:
df['observed_gap_semesters'].value_counts(dropna=False)

observed_gap_semesters
0       384164
<NA>     68510
1         3267
2          386
3           88
4           31
5            7
Name: count, dtype: Int64

In [6]:
df['observed_gap_semesters'].value_counts(dropna=False)

observed_gap_semesters
0       384164
<NA>     68510
1         3267
2          386
3           88
4           31
5            7
Name: count, dtype: Int64

10815.111
3472.111
3470.111

In [7]:
df[df['total_fail_credits']==713.5]

,student_course_id,student_id,course_id,part_id,grade_id,final_mark,points,course_name_sl,degree_id,degree_name_sl_course,faculty_id,course_credits,course_outcome_status,attempt_number,student_status_id,degree_name_sl_status,start_part_id,finish_part_id,grade_version_id,prev_gpa_points,last_enrolled_gpa,observed_gap_semesters,gpa_points,start_agpa_points,start_total_in_courses,start_total_in_credits,end_total_in_courses,end_total_in_credits,end_agpa_points,semester_reg_courses,semester_reg_credits,semester_pass_courses,semester_pass_credits,semester_fail_courses,semester_fail_credits,total_semesters,total_reg_courses,total_reg_credits,total_pass_courses,total_pass_credits,total_fail_courses,total_fail_credits,reg_total_semesters,finish_status,degree_credits_count,start_level_name_short,end_level_name_short,plan_degree_course_id,plan_course_type_id,plan_requirement_type_id,plan_requirement_type_sl,plan_course_name_sl,plan_course_official_sl,plan_degree_name_sl,plan_year_order,plan_semester_order,plan_course_credits,plan_credits_count,plan_active,plan_match
439608,2573279.111,3470.111,1093.111,20232,978.111,81,3.0,الامتحان الوطني,2.111,دكتور في الطب,2.111,24.0,pass,1,371794.111,دكتور في الطب,20161,20232,3.111,0.0,0.0,1,3.0,2.11,62,227.0,63,251.0,2.27,1,24.0,1,24.0,0,0.0,49,278,996.0,77,260.5,193,713.5,49,GRADUATED,251.0,6,6,1445.111,2,5,متطلبات الشهادة الإجبارية,الامتحان الوطني,الامتحان الوطني,دكتور في الطب,6,2,24.0,210.0,A,True
439609,2201832.111,3470.111,664.111,20213,974.111,99,4.0,رسالة التخرج,2.111,دكتور في الطب,2.111,3.0,pass,1,321187.111,دكتور في الطب,20161,20232,3.111,0.0,0.0,0,4.0,2.06,61,224.0,62,227.0,2.11,1,3.0,1,3.0,0,0.0,46,273,981.0,76,257.5,193,713.5,46,GRADUATED,251.0,6,6,248.111,2,3,متطلبات الكلية الإجبارية,رسالة التخرج,رسالة التخرج,دكتور في الطب,5,1,3.0,22.0,A,True
439610,1549096.111,3470.111,689.111,20203,982.111,60,2.0,الأحياء الدقيقة (1),2.111,دكتور في الطب,2.111,4.0,pass,1,301185.111,دكتور في الطب,20161,20232,3.111,0.67,0.67,0,1.88,1.57,56,198.0,58,206.0,1.7,2,8.0,2,8.0,0,0.0,43,263,943.0,71,231.5,193,713.5,43,GRADUATED,251.0,6,6,348.111,3,5,متطلبات الشهادة الإجبارية,الأحياء الدقيقة (1),الأحياء الدقيقة (1),دكتور في الطب,2,2,4.0,210.0,A,True
439612,1549095.111,3470.111,690.111,20203,983.111,59,1.75,الأحياء الدقيقة (2),2.111,دكتور في الطب,2.111,4.0,pass,2,301185.111,دكتور في الطب,20161,20232,3.111,0.67,0.67,0,1.88,1.57,56,198.0,58,206.0,1.7,2,8.0,2,8.0,0,0.0,43,263,943.0,71,231.5,193,713.5,43,GRADUATED,251.0,6,6,349.111,3,5,متطلبات الشهادة الإجبارية,الأحياء الدقيقة (2),الأحياء الدقيقة (2),دكتور في الطب,3,1,4.0,210.0,A,True
439614,1559322.111,3470.111,696.111,20211,981.111,67,2.25,الطب الباطني (2),2.111,دكتور في الطب,2.111,6.0,pass,2,308846.111,دكتور في الطب,20161,20232,3.111,1.88,1.88,0,2.25,1.7,58,206.0,61,224.0,2.06,3,18.0,3,18.0,0,0.0,44,265,951.0,73,239.5,193,713.5,44,GRADUATED,251.0,6,6,360.111,3,5,متطلبات الشهادة الإجبارية,الطب الباطني (2),الطب الباطني (2),دكتور في الطب,4,1,6.0,210.0,A,True
439618,1559323.111,3470.111,699.111,20211,981.111,66,2.25,الطب الباطني (5),2.111,دكتور في الطب,2.111,6.0,pass,3,308846.111,دكتور في الطب,20161,20232,3.111,1.88,1.88,0,2.25,1.7,58,206.0,61,224.0,2.06,3,18.0,3,18.0,0,0.0,44,265,951.0,73,239.5,193,713.5,44,GRADUATED,251.0,6,6,363.111,3,5,متطلبات الشهادة الإجبارية,الطب الباطني (5),الطب الباطني (5),دكتور في الطب,5,1,6.0,210.0,A,True
439619,1559324.111,3470.111,709.111,20211,981.111,67,2.25,جراحة (2),2.111,دكتور في الطب,2.111,6.0,pass,1,308846.111,دكتور في الطب,20161,20232,3.111,1.88,1.88,0,2.25,1.7,58,206.0,61,224.0,2.06,3,18.0,3,18.0,0,0.0,44,265,951.0,73,239.5,193,713.5,44,GRADUATED,251.0,6,6,386.111,3,5,متطلبات الشهادة الإجبارية,جراحة (2),جراحة (2),دكتور في الطب,4,1,6.0,210.0,A,True

In [8]:
df.describe()

,part_id,final_mark,points,course_credits,attempt_number,start_part_id,finish_part_id,prev_gpa_points,last_enrolled_gpa,observed_gap_semesters,gpa_points,start_agpa_points,start_total_in_courses,start_total_in_credits,end_total_in_courses,end_total_in_credits,end_agpa_points,semester_reg_courses,semester_reg_credits,semester_pass_courses,semester_pass_credits,semester_fail_courses,semester_fail_credits,total_semesters,total_reg_courses,total_reg_credits,total_pass_courses,total_pass_credits,total_fail_courses,total_fail_credits,reg_total_semesters,degree_credits_count,plan_year_order,plan_semester_order,plan_course_credits,plan_credits_count
count,456453.0,456453.0,456453.0,456453.0,456453.0,456453.0,197427.0,412163.0,411686.0,387943.0,456453.0,456453.0,456453.0,456453.0,456453.0,456453.0,456453.0,456453.0,456453.0,456453.0,456453.0,456453.0,456453.0,456453.0,456453.0,456453.0,456453.0,456453.0,456453.0,456453.0,456453.0,456453.0,456307.0,456307.0,456386.0,456386.0
mean,20226.812254,69.977336,2.316207,2.896384,1.123636,20202.562855,20233.589575,2.247115,2.263896,0.011502,2.288979,1.967002,28.415848,78.865023,33.611721,93.365247,2.422564,5.817972,16.195665,5.080392,14.120211,0.527362,1.500873,8.319549,35.885408,100.326404,28.928455,80.635306,5.043845,14.424451,8.139092,186.142468,2.754681,1.49644,2.896441,111.824578
std,16.522975,15.944697,0.974245,1.444591,0.436635,26.39864,13.013039,0.836638,0.815299,0.12665,0.741643,1.035529,20.364772,56.687091,20.618521,57.207285,0.514375,1.621575,4.327027,1.946134,5.302774,0.975455,2.879544,5.937926,27.948905,78.938556,20.891621,58.273682,9.966536,29.728795,5.735402,39.669579,1.428916,0.499988,1.44467,71.570098
min,20201.0,0.0,0.0,0.0,1.0,20111.0,20132.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,72.0,1.0,1.0,0.0,4.0
25%,20212.0,60.0,2.0,2.0,1.0,20191.0,20223.0,1.84,1.85,0.0,1.87,1.86,11.0,30.0,16.0,44.0,2.1,5.0,15.0,4.0,11.0,0.0,0.0,4.0,13.0,36.0,11.0,31.0,0.0,0.0,4.0,173.0,1.0,1.0,2.0,48.0
50%,20231.0,71.0,2.5,3.0,1.0,20201.0,20233.0,2.38,2.39,0.0,2.39,2.23,27.0,74.0,32.0,88.0,2.39,6.0,17.0,5.0,15.0,0.0,0.0,7.0,32.0,89.0,27.0,75.0,1.0,3.0,7.0,180.0,3.0,1.0,3.0,129.0
75%,20241.0,82.0,3.0,3.0,1.0,20221.0,20242.0,2.83,2.83,0.0,2.82,2.64,44.0,123.0,50.0,138.0,2.76,7.0,18.0,6.0,18.0,1.0,2.0,12.0,53.0,149.0,45.0,125.0,6.0,16.0,12.0,185.0,4.0,2.0,3.0,170.0
max,20253.0,100.0,4.0,24.0,11.0,20252.0,20252.0,4.0,4.0,5.0,4.0,4.0,81.0,252.0,83.0,257.0,4.0,12.0,49.0,12.0,49.0,11.0,47.5,53.0,278.0,1001.5,106.0,334.0,193.0,713.5,50.0,251.0,6.0,2.0,24.0,210.0

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 456453 entries, 0 to 456452
Data columns (total 60 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   student_course_id         456453 non-null  string
 1   student_id                456453 non-null  string
 2   course_id                 456453 non-null  string
 3   part_id                   456453 non-null  Int64
 4   grade_id                  456453 non-null  string
 5   final_mark                456453 non-null  Int64
 6   points                    456453 non-null  Float64
 7   course_name_sl            456453 non-null  string
 8   degree_id                 456453 non-null  string
 9   degree_name_sl_course     456453 non-null  string
 10  faculty_id                456453 non-null  string
 11  course_credits            456453 non-null  Float64
 12  course_outcome_status     456453 non-null  str
 13  attempt_number            456453 non-null  Int64
 14  student_status_id         456453 non-null  string
 15  degree_name_sl_status     456453 non-null  string
 16  start_part_id             456453 non-null  Int64
 17  finish_part_id            197427 non-null  Int64
 18  grade_version_id          456453 non-null  string
 19  prev_gpa_points           412163 non-null  Float64
 20  last_enrolled_gpa         411686 non-null  Float64
 21  observed_gap_semesters    387943 non-null  Int64
 22  gpa_points                456453 non-null  Float64
 23  start_agpa_points         456453 non-null  Float64
 24  start_total_in_courses    456453 non-null  Int64
 25  start_total_in_credits    456453 non-null  Float64
 26  end_total_in_courses      456453 non-null  Int64
 27  end_total_in_credits      456453 non-null  Float64
 28  end_agpa_points           456453 non-null  Float64
 29  semester_reg_courses      456453 non-null  Int64
 30  semester_reg_credits      456453 non-null  Float64
 31  semester_pass_courses     456453 non-null  Int64
 32  semester_pass_credits     456453 non-null  Float64
 33  semester_fail_courses     456453 non-null  Int64
 34  semester_fail_credits     456453 non-null  Float64
 35  total_semesters           456453 non-null  Int64
 36  total_reg_courses         456453 non-null  Int64
 37  total_reg_credits         456453 non-null  Float64
 38  total_pass_courses        456453 non-null  Int64
 39  total_pass_credits        456453 non-null  Float64
 40  total_fail_courses        456453 non-null  Int64
 41  total_fail_credits        456453 non-null  Float64
 42  reg_total_semesters       456453 non-null  Int64
 43  finish_status             197795 non-null  string
 44  degree_credits_count      456453 non-null  Float64
 45  start_level_name_short    456453 non-null  string
 46  end_level_name_short      456453 non-null  string
 47  plan_degree_course_id     456386 non-null  string
 48  plan_course_type_id       456386 non-null  string
 49  plan_requirement_type_id  456386 non-null  string
 50  plan_requirement_type_sl  456386 non-null  string
 51  plan_course_name_sl       456386 non-null  string
 52  plan_course_official_sl   456386 non-null  string
 53  plan_degree_name_sl       456386 non-null  string
 54  plan_year_order           456307 non-null  Int64
 55  plan_semester_order       456307 non-null  Int64
 56  plan_course_credits       456386 non-null  Float64
 57  plan_credits_count        456386 non-null  Float64
 58  plan_active               456386 non-null  string
 59  plan_match                456453 non-null  bool
dtypes: Float64(18), Int64(18), bool(1), str(1), string(22)
memory usage: 379.4 MB